apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-blue-deployment
  labels:
    app: nginx-app
    version: blue
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx-app
      version: blue
  template:
    metadata:
      labels:
        app: nginx-app
        version: blue
    spec:
      containers:
      - name: nginx
        image: anusha2429/nginx-demo:latest
        ports:
        - containerPort: 80

