name: CI/CD Pipeline for Nginx

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repository
      uses: actions/checkout@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build the Docker image
      run: docker build -t your-dockerhub-username/nginx-demo:latest .

    - name: Push the Docker image
      run: docker push your-dockerhub-username/nginx-demo:latest

  deploy:
  runs-on: ubuntu-latest
  needs: build
  steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-south-1

    - name: Create kubeconfig from secret
      run: echo "${{ secrets.KUBECONFIG_DATA_RAW }}" > kubeconfig

    - name: Check kubeconfig file
      run: |
        if [ -f kubeconfig ]; then
          echo "kubeconfig file created successfully."
          cat kubeconfig
        else
          echo "kubeconfig file not created."
          exit 1
        fi

    - name: Get cluster info
      run: |
        kubectl --kubeconfig kubeconfig cluster-info

    - name: Deploy to Kubernetes
      run: |
        kubectl --kubeconfig kubeconfig apply -f k8s-deployment.yaml
      
